baseurl = "/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "shadocs"
categories = ['Cases', 'Onboarding', '']
tags = ['Virtual Server', 'Direct Link']

currentVersion     = "latest"
siteContentOrder = "weight"
[taxonomies]
  category = 'categories'
  tag = 'tags'

[params.taxonomies]
    [params.taxonomies.categories]
    icon = "fa-solid fa-table-cells"



[outputs]
  home = ["HTML","RSS", "JSON"]
  section =["HTML","RSS", "JSON"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true