# how to add widgets: https://www.netlifycms.org/docs/widgets/


backend:
  name: git-gateway
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "cases" # Used in routes, e.g., /admin/collections/blog
    label: "Cases" # Used in the UI
    folder: "/content/cases" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "Draft", widget: "boolean"}
      - {label: "Categories", name: "Categories", widget: "select", options: [{ label: "Cases", value: "cases"} ] }
      - {label: "Tags", name: "Tags", widget: "select", options: [{ label: "Direct Link", value: "direct-link"}, {label: "Virtual Server", value: "virtual-server"} ]}
      # - {label: "Problem Description",  name: "Problem Description", widget: "text"}
      - {label: "Screenshots", name: "Screenshots", widget: "file"}
      # - {label: "Logs requested (from Ops and Support) & Collected by VMLC", name: "Logs Requested", widget: "text" }
      # - {label: "Workaround if any", name: "Workaround if any", widget: "text"}
      # - {label: "Solution", name: "Solution", widget: "text"}
      - {label: "Case Details", name: "body", widget: "markdown", default: "<!-- Note White Space Matters!! --><br><!-- Problem Description Section --># Problem Description<!-- End of Problem Description Section --><br>***<!-- Screenshots Section --><br># Screenshots<!-- ![I'm an image](/images/favicon.png) --><!-- End Of Screenshots Section --><br>***<!-- Logs Requested Section --><br># Logs Requested<!-- End Of Logs Requested Section --><br>***<!-- Work Arounds Section --><br># Work Arounds<!-- End Of Work Arounds Section --><br>***<!-- Solution Section --><br># Solution<!-- End Of Solution Section -->"}
